import jsPDF from 'jspdf';

interface ExamPDFOptions {
  classLevel: number;
  subject: string;
  topic?: string;
  content: string;
}

export function generateExamPDF({ classLevel, subject, topic, content }: ExamPDFOptions): void {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace: number = 20) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
      addHeader();
    }
  };

  // Add header
  const addHeader = () => {
    pdf.setFillColor(99, 102, 241); // Primary color
    pdf.rect(0, 0, pageWidth, 25, 'F');
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('WeakBuddyStudy - Mock Exam Paper', pageWidth / 2, 12, { align: 'center' });
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Class ${classLevel} | ${subject}${topic ? ` | ${topic}` : ''}`, pageWidth / 2, 20, { align: 'center' });
    
    yPosition = 35;
  };

  // Add footer
  const addFooter = () => {
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(128, 128, 128);
      pdf.text(
        `Page ${i} of ${pageCount} | Generated by WeakBuddyStudy`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }
  };

  // Add exam info box
  const addExamInfo = () => {
    pdf.setFillColor(249, 250, 251);
    pdf.roundedRect(margin, yPosition, contentWidth, 25, 3, 3, 'F');
    
    pdf.setTextColor(55, 65, 81);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    
    const date = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
    });
    
    pdf.text(`Date: ${date}`, margin + 5, yPosition + 8);
    pdf.text(`Subject: ${subject}`, margin + 5, yPosition + 15);
    pdf.text(`Class: ${classLevel}`, margin + 5, yPosition + 22);
    
    pdf.text(`Time: 2 Hours`, pageWidth / 2, yPosition + 8);
    pdf.text(`Maximum Marks: 50`, pageWidth / 2, yPosition + 15);
    
    yPosition += 35;
  };

  // Parse and add content
  const addContent = () => {
    // Clean up markdown for PDF
    const lines = content.split('\n');
    
    for (const line of lines) {
      const trimmedLine = line.trim();
      
      if (!trimmedLine) {
        yPosition += 3;
        continue;
      }

      checkPageBreak();

      // Section headers (## or ###)
      if (trimmedLine.startsWith('## ') || trimmedLine.startsWith('### ')) {
        const headerText = trimmedLine.replace(/^#{2,3}\s*/, '').replace(/\*\*/g, '');
        
        yPosition += 5;
        pdf.setFillColor(99, 102, 241);
        pdf.roundedRect(margin, yPosition, contentWidth, 10, 2, 2, 'F');
        
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text(headerText, margin + 5, yPosition + 7);
        
        yPosition += 15;
        continue;
      }

      // Main header (#)
      if (trimmedLine.startsWith('# ')) {
        const headerText = trimmedLine.replace(/^#\s*/, '').replace(/\*\*/g, '');
        
        pdf.setTextColor(55, 65, 81);
        pdf.setFontSize(14);
        pdf.setFont('helvetica', 'bold');
        pdf.text(headerText, margin, yPosition);
        
        yPosition += 10;
        continue;
      }

      // Bold text lines
      if (trimmedLine.startsWith('**') && trimmedLine.endsWith('**')) {
        const boldText = trimmedLine.replace(/\*\*/g, '');
        
        pdf.setTextColor(55, 65, 81);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        
        const splitText = pdf.splitTextToSize(boldText, contentWidth);
        pdf.text(splitText, margin, yPosition);
        yPosition += splitText.length * 6 + 2;
        continue;
      }

      // List items
      if (trimmedLine.match(/^[\-\*\d\.]+\s/)) {
        const listText = trimmedLine
          .replace(/^[\-\*]\s/, '• ')
          .replace(/^\d+\.\s/, (match) => match)
          .replace(/\*\*/g, '');
        
        pdf.setTextColor(55, 65, 81);
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        
        const splitText = pdf.splitTextToSize(listText, contentWidth - 5);
        pdf.text(splitText, margin + 3, yPosition);
        yPosition += splitText.length * 5 + 2;
        continue;
      }

      // Regular text
      const cleanText = trimmedLine.replace(/\*\*/g, '').replace(/\*/g, '');
      
      pdf.setTextColor(55, 65, 81);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      
      const splitText = pdf.splitTextToSize(cleanText, contentWidth);
      pdf.text(splitText, margin, yPosition);
      yPosition += splitText.length * 5 + 2;
    }
  };

  // Generate PDF
  addHeader();
  addExamInfo();
  addContent();
  addFooter();

  // Download
  const filename = `MockExam_Class${classLevel}_${subject}${topic ? `_${topic.replace(/\s+/g, '_')}` : ''}.pdf`;
  pdf.save(filename);
}
